import Footer from "@/components/layout/Footer";
import NavBar from "@/components/layout/NavBar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Local font imports from /public/fonts
const suisse = localFont({
  src: [
    { path: "../public/fonts/SuisseMedium.ttf", weight: "500", style: "normal" },
    { path: "../public/fonts/SuisseBold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-suisse",
  display: "swap",
});

const suisseMono = localFont({
  src: "../public/fonts/SuisseMono.ttf",
  variable: "--font-suisse-mono",
  display: "swap",
});

const tempting = localFont({
  src: "../public/fonts/Tempting.ttf",
  variable: "--font-tempting",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${suisse.variable} ${suisseMono.variable} ${tempting.variable} antialiased`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
